#!/bin/bash

echo "🚀 English Voice Platform Deployment Helper"
echo "=========================================="

echo ""
echo "📋 Prerequisites Checklist:"
echo "1. GitHub repository with your code"
echo "2. Vercel account (vercel.com)"
echo "3. Render account (render.com)"
echo "4. MongoDB Atlas account"
echo "5. Clerk account for authentication"
echo ""

echo "🔧 Environment Variables Needed:"
echo ""
echo "For Render (Backend):"
echo "- MONGODB_URI"
echo "- CLERK_SECRET_KEY"
echo "- CLERK_PUBLISHABLE_KEY"
echo "- CLIENT_URL (will be your Vercel URL)"
echo "- PORT"
echo "- JWT_SECRET"
echo ""
echo "For Vercel (Frontend):"
echo "- VITE_CLERK_PUBLISHABLE_KEY"
echo "- VITE_API_URL (will be your Render URL)"
echo "- VITE_SERVER_URL (will be your Render URL)"
echo ""

echo "📖 Next Steps:"
echo "1. Read DEPLOYMENT.md for detailed instructions"
echo "2. Set up MongoDB Atlas database"
echo "3. Deploy backend to Render"
echo "4. Deploy frontend to Vercel"
echo "5. Update environment variables with actual URLs"
echo "6. Configure Clerk settings"
echo ""

echo "✅ Files created for deployment:"
echo "- server/env.example (environment variables template)"
echo "- client/env.example (environment variables template)"
echo "- client/vercel.json (Vercel configuration)"
echo "- server/render.yaml (Render configuration)"
echo "- DEPLOYMENT.md (detailed deployment guide)"
echo ""

echo "🎯 Ready to deploy! Follow the instructions in DEPLOYMENT.md" 